### ISSUE TITLE
Breaks Calendar Sync via CalDav Beta

### ISSUE THREAD

**Issue by schniepp** [nickv-nextcloud/twofactor_nextcloud_notification#151]
### Steps to reproduce
1. Install Caldav Sync Free Beta on Android phone from Google Play Appstore
2. Sync Calendar with Nextcloud, confirm that sync works
3. Turn on 2FA via Nextcloud Notification for the same user that is set up for the sync

### Expected behaviour
The sync will either go through normally, or will require an authorization via nc notification

### Actual behaviour
Sync fails with an error, no notification for 2FA is issued

### Server configuration
**Operating system**: ubuntu 18.04
**Web server:** apache
**Database:** MySQL
**PHP version:** 7.2
**Nextcloud version:** 15.0.7
**Where did you install Nextcloud from:** directly from ZIP file

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - audioplayer: 2.7.0
  - bookmarks: 1.0.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - carnet: 0.15.2
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - deck: 0.6.1
  - defaultlinkopen: 1.2.0
  - drawio: 0.9.3
  - event_update_notification: 0.3.4
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_inotify: 0.1.4
  - files_linkeditor: 1.0.10
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.3
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trackdownloads: 1.4.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - music: 0.9.5
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocdownloader: 1.7.0
  - ocsms: 2.1.1
  - passman: 2.2.1
  - password_policy: 1.5.0
  - passwords: 2019.4.2
  - polls: 0.10.2
  - previewgenerator: 2.1.0
  - provisioning_api: 1.5.0
  - radio: 0.6.4
  - ransomware_detection: 0.4.3
  - ransomware_protection: 1.3.0
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - sharerenamer: 2.6.0
  - spreed: 5.0.3
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.1.1
  - updatenotification: 1.5.0
  - weather: 1.5.5
  - workflowengine: 1.5.0

**Nextcloud configuration:** will provide if needed

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome
**Operating system:** ubuntu/android

**Comment by rullzer** [comment]
Yes this is a result of enabling two factor authentication. You then need to create an app password.
