### ISSUE TITLE
NC 17 login problem

### ISSUE THREAD

**Issue by tobiasKaminsky** [nickv-nextcloud/twofactor_nextcloud_notification#199]
I do get "500 internal server error" when trying to log in.

log says:
`
{"reqId":"OXKDhbhuteDWP8G0lxmA","level":3,"time":"2019-08-20T08:37:45+00:00","remoteAddr":"95.222.212.109","user":"test","app":"index","method":"GET","url":"\/login\/challenge\/twofactor_nextcloud_notification","message":{"Exception":"TypeError","Message":"Argument 2 passed to OC\\Notification\\Notification::setObject() must be of the type string, int given, called in \/srv\/nextcloud\/apps\/twofactor_nextcloud_notification\/lib\/Service\/NotificationManager.php on line 59","Code":0,"Trace":[{"file":"\/srv\/nextcloud\/apps\/twofactor_nextcloud_notification\/lib\/Service\/NotificationManager.php","line":59,"function":"setObject","class":"OC\\Notification\\Notification","type":"->","args":["2fa_id",57]},{"file":"\/srv\/nextcloud\/apps\/twofactor_nextcloud_notification\/lib\/Service\/TokenManager.php","line":99,"function":"newNotification","class":"OCA\\TwoFactorNextcloudNotification\\Service\\NotificationManager","type":"->","args":[{"id":57,"__class__":"OCA\\TwoFactorNextcloudNotification\\Db\\Token"}]},{"file":"\/srv\/nextcloud\/apps\/twofactor_nextcloud_notification\/lib\/Provider\/NotificationProvider.php","line":93,"function":"generate","class":"OCA\\TwoFactorNextcloudNotification\\Service\\TokenManager","type":"->","args":["test"]},{"file":"\/srv\/nextcloud\/core\/Controller\/TwoFactorChallengeController.php","line":156,"function":"getTemplate","class":"OCA\\TwoFactorNextcloudNotification\\Provider\\NotificationProvider","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"\/srv\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"showChallenge","class":"OC\\Core\\Controller\\TwoFactorChallengeController","type":"->","args":["twofactor_nextcloud_notification",null]},{"file":"\/srv\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\TwoFactorChallengeController"},"showChallenge"]},{"file":"\/srv\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\TwoFactorChallengeController"},"showChallenge"]},{"file":"\/srv\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\TwoFactorChallengeController","showChallenge",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"challengeProviderId":"twofactor_nextcloud_notification","_route":"core.TwoFactorChallenge.showChallenge"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"challengeProviderId":"twofactor_nextcloud_notification","_route":"core.TwoFactorChallenge.showChallenge"}]},{"file":"\/srv\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"challengeProviderId":"twofactor_nextcloud_notification","_route":"core.TwoFactorChallenge.showChallenge"}]},{"file":"\/srv\/nextcloud\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login\/challenge\/twofactor_nextcloud_notification"]},{"file":"\/srv\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/srv\/nextcloud\/lib\/private\/Notification\/Notification.php","Line":199,"CustomMessage":"--"},"userAgent":"Motorola Moto G4 Plus (Android)","version":"17.0.0.2"}
`

**Comment by nursoda** [comment]
I still have this issue with 2.1.1 on NC17RC1– what am I missing?
