### ISSUE TITLE
Setup translations

### ISSUE THREAD

**Issue by rullzer** [nickv-nextcloud/twofactor_nextcloud_notification#20]

**Comment by rullzer** [comment]
@MorrisJobke could you help us out with that?

**Comment by MorrisJobke** [comment]
Could you make @nextcloud-bot admin here? So it can push even if there is a protected branch + reviews required?

**Comment by MorrisJobke** [comment]
Otherwise "write" is enough (if no checks are enforced)

**Comment by rullzer** [comment]
currently no checks are enforced. BUt hopefully they will be at some point :P

**Comment by rullzer** [comment]
:heavy_check_mark: @nextcloud-bot is admin
