### ISSUE TITLE
后台JS翻译有问题

### ISSUE THREAD

**Issue by yxwmok** [nickv-nextcloud/twofactor_nextcloud_notification#204]
后台JS没有将英文翻译为中文，检查setting.js中twofactor_nextcloud_notification写成twofactor_nextcloud_notifications了

**Comment by nickvergessen** [comment]
Please always report issues in english, thanks

> JS does not translate English into Chinese. Check that twofactor_nextcloud_notification in setting.js is written as twofactor_nextcloud_notifications.

**Comment by rullzer** [comment]
Our translations are handled on transifex. Please join there.
