### ISSUE TITLE
Question: Push notification to Android

### ISSUE THREAD

**Issue by derritter88** [nickv-nextcloud/twofactor_nextcloud_notification#318]
Hi there,

I have tried to uses Notification as another MFA possibility but I am not sure if this would work with Nextcloud app on Android.

### Prerequisites:
1. Nextcloud Android app from F-Droid
2. Nextcloud account

### Steps to reproduce
1. Login at Nextcloud on desktop/laptop.
2. Select push notification as a 2FA.
3. Wait for pushed notification on mobile phone

### Expected behaviour
Nextcloud app on mobile phone should ask if I confirm the login request (or if I'd like to deny).
After confirmation I will get access to my Nextcloud.

### Actual behaviour
I do not get any notification on my mobile phone - even if I have the Nextcloud app opened.

### Server configuration

**Operating system**: Ubuntu 18.04.4

**Web server:** Apache2 ( 2.4.41-1+ubuntu18.04.1+deb.sury.org+5)

**Database:** Postgresql 10

**PHP version:** 7.3-FPM

**Nextcloud version:** 18.0.3

**Where did you install Nextcloud from:** nextcloud.com

**List of activated apps:** 
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - analytics: 2.2.1
  - breezedark: 18.0.11
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.3.0
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - gpxpod: 4.2.1
  - groupfolders: 6.0.5
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - metadata: 0.11.1
  - news: 14.1.3
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hks-projekt.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.hks-projekt.at",
        "dbtype": "pgsql",
        "version": "18.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "theme": "",
        "asset-pipeline.enable": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "session_lifetime": 600,
        "session_keepalive": false,
        "trashbin_retention_obligation": "auto, 7",
        "mysql.utf8mb4": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": 104857600,
        "quota_include_external_storage": false,
        "app_install_overwrite": [
            "files_fulltextsearch",
            "bruteforcesettings",
            "checksum",
            "contacts",
            "drawio"
        ],
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by rullzer** [comment]
There are no push notifications in fdroid as far as I know.
@TobiasKaminsky for more info

**Comment by tobiasKaminsky** [comment]
No, fdroid is pure OSS and thus we cannot integrate push into it.
To still use 2FA with notifications just open up the app and select "notifications" to approve it.

**Comment by derritter88** [comment]
Okay - so thanks for clarification!
