### ISSUE TITLE
No notification is received.

### ISSUE THREAD

**Issue by resoli** [nickv-nextcloud/twofactor_nextcloud_notification#328]
Hello

One one of my Nextcloud 18.0.4 installations twofactor_nextcloud_notification does not send any push notification. 

- 2FA is enabled and twofactor_totp is enabled and regularly working. 
- LDAP users enabled and working, this is one difference rispect other working 18.0.4 instances. (But twofactor_nextcloud_notification does not work when a non ldap user tries to login)
- twofactor_admin is installed and working

nextcloud.log apparently does not shows any error apparently, but tracing network traffic I see that no connection to "push-notifications.nextcloud.com" is attempted upon login. (as happens on working istances).

Notification is present in Android Nextcloud "Notifications" menu item, and login works when selected. No notifications is found in NC desktop sync client log.

bye,
rob

**Comment by nickvergessen** [comment]
Please check with the newest version of the App, Nextcloud and the mobile apps
