### ISSUE TITLE
TOTP Notification on MacOS?

### ISSUE THREAD

**Issue by b-pfl** [nickv-nextcloud/twofactor_nextcloud_notification#337]
### Steps to reproduce
1. Install nextcloud 18
2. Install the Two-Factor Authentication via Nextcloud notification App
3. Create an ordinary Nextcloud account and set up 2FA using this app
4. Connect e.g. an Android client using the account from step 3
5. Connect the latest MacOS client (2.6.4, March 2020) 
6. Try to sign in (e.g. from Browser) and select the Notification App as 2FA option

### Expected behaviour
When signing in (e.g. via a browser), notifications should show up on all connected clients (Android and MacOS)

### Actual behaviour
- Notifications work well on Android
- No notifications on MacOS

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server**: Apache 2.4

**Database**: MySQL 5.7.30

**PHP version:** 7.4.6

**Nextcloud version:** 18.0.5

**Where did you install Nextcloud from:** manually

**List of activated apps:** quite a few

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
I guess it's related to #468 ?
I don't have a Mac to test, but maybe you can retry when I confirmed iOS to work

**Comment by b-pfl** [comment]
@nickvergessen Sorry that I forgot to react earlier. At least on 3.2.0 (Mac) this seems to work now. I don't see that a notification pops up automatically, but when clicking the Taskbar icon, the message and button(s) appear and I can sign in as expected.
