### ISSUE TITLE
failed to execute action

### ISSUE THREAD

**Issue by morph027** [nickv-nextcloud/twofactor_nextcloud_notification#34]
Latest version of everything, the Android app gives me a toast `Failed to execute action!` when hitting _Annehmen_. The login does work however.

**Comment by rullzer** [comment]
Yeah it is the android app not accepting the 204 response.
I'm in contact with the android devs what the quickest way forward is

**Comment by tobiasKaminsky** [comment]
New stable release will be Monday/Tuesday with this fix included

**Comment by rullzer** [comment]
New client is released.
Let me close this.
