### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by Aedilius** [nickv-nextcloud/twofactor_nextcloud_notification#342]
I cut the branch under my butt because I have activated 2FA on my Admin account and logged out for testing without a second active session. I still have a ftp access, but I am a beginner and do not know where to insert this line and how to get my UserID

./occ twofactorauth:disable <your userid>

Do you have a helpful tip?
Greeting

**Comment by boingo-00** [comment]
You need access to server console
I'm not sure about system details, so I leave example of command:
`sudo -u www-data php /var/www/nextcloud/occ twofactorauth:disable`
Replace `www-data` with web-server username and `/var/www/nextcloud/` with nextcloud install path

**Comment by Aedilius** [comment]
Thank you very much for your answer.
I have no Linux environment available and the cloud is on my webspace without server access.

But I never stop learning and from now on there are always two admin accesses. Now I have deleted the cloud, created a new one and put the data of the Nextcloud directory on my PC back into the cloud.
Now everything is okay again until the next GAU :-))

**Comment by rullzer** [comment]
Yes you'd need console access. Or mess with the DB.
Be sure to create 2FA backup codes next time.
