### ISSUE TITLE
No notification is received on desktop client (on Linux)

### ISSUE THREAD

**Issue by errotu** [nickv-nextcloud/twofactor_nextcloud_notification#367]
First of all, thanks for your great work! Unfortunately, notification as two-factor-method only works for me on android, not with my desktop client.

### Steps to reproduce
1. Use notification as two-factor-authentication
2. Wait for notification appearing on desktop client
3. No notification appears

### Expected behaviour
A desktop notification should be shown with the possibility to accept the login

### Actual behaviour
No notification appears

**Operating system**: Ubuntu 20.04 with GNOME Shell 3.36.3

**Nextcloud version:** Nextcloud 18.0.6 with Version 2.6.2-1build1 as client

**Comment by iGadget** [comment]
Same here, but in my case it's even worse - For me it only works on the web interface. I'm not getting any notification on Android either. How did you make this work, @errotu ?

**Comment by nickvergessen** [comment]
Works fine here, can you try with the latest version of Nextcloud and the app?

**Comment by errotu** [comment]
I just tried it unsuccessfully with Nextcloud Server Version 21.0.3 and Desktop Version 3.1.1 (Ubuntu). Where should the notification appear on the desktop? I only see it in the web interface.

**Comment by nickvergessen** [comment]
Are you by chance using a language like russian?
Then I think this is because of #557
