### ISSUE TITLE
Not working with Internet Explorer

### ISSUE THREAD

**Issue by michag86** [nickv-nextcloud/twofactor_nextcloud_notification#44]
### Steps to reproduce
1. Enable twofactor notification for a user
2. Login with this user
3. After selecting "Authentifiziere dich über ein Gerät das schon mit deinem Konto verbunden ist ", the notification is sent successfully

### Expected behaviour
Login works after accept

### Actual behaviour
It is not showing "Bitte akzeptiere die Anfrage auf einem deiner angemeldeten Geräte. Sie werden automatisch weitergeleitet sobald die Anmeldung akzeptiert wurde. "
After Accept in the app, nothing happens.

![grafik](https://user-images.githubusercontent.com/6691165/48149789-4d659780-e2bd-11e8-95e8-17aa0aca7eb1.png)

Error Console shows:
SCRIPT1002: Syntaxfehler
Datei: challenge.js, Zeile: 33, Spalte: 135

### Versions
Nextcloud 14.0.3
All apps up to date.

### Browser
It's working with Firefox but not with Internet Explorer

**Comment by rullzer** [comment]
This app currently does not support IE.
However PR's to fix this are of course welcome.

**Comment by michag86** [comment]
It has to do something with this:

function T(t){const e=OC.generateUrl("/apps/twofactor_nextcloud_notification/settings/state"),n={state:t};return A.a.post(e,n).then(**t=>t.data**)}

Here is written, that "arrow functions" not working with IE:
https://stackoverflow.com/questions/40216015/arrow-function-not-working-in-ie-why

But I don't know how to fix this for t=>t.data

**Comment by rullzer** [comment]
@ChristophWurst I guess we could also enable babel here right?

**Comment by ChristophWurst** [comment]
there's already babel. @skjnldsv what was the trick to have the proper transpilation? a .babelrc? We discussed this before christmas but I can't recall ;)

**Comment by skjnldsv** [comment]
Ahaha, yes, babel with this: https://github.com/nextcloud/server/blob/bd697f63bde71ee84b591eaa4b54f128125f9f45/apps/accessibility/.babelrc.js

**Comment by rullzer** [comment]
Thnx I'll fix that then :)

**Comment by rullzer** [comment]
I'll release a new version this evneing. Since I do not have IE11 I can't really test it. But hopefully you can provide feedback @michag86

**Comment by rullzer** [comment]
v1.0.2 is out. @michag86 could you check if this works?

**Comment by michag86** [comment]
I will check it tomorrow.

**Comment by rullzer** [comment]
I get the same error locally on an IE test instance.
@ChristophWurst will have another look next week :)

**Comment by ChristophWurst** [comment]
This is weird. I tried to apply my usual trick here as well (https://github.com/nextcloud/twofactor_totp/pull/426) but you've already added the babelrc file and it still does not transpile arrow functions.

The bundle shows that the arrow function is used in the `is-buffer` package, which is a dependency of `axios`. For some reason the one in TOTP does not have arrow functions while this has.

**Comment by ChristophWurst** [comment]
Bingo https://github.com/visionmedia/debug/issues/668#issuecomment-452481480!

**Comment by ChristophWurst** [comment]
I tried to make babel transpile the module but failed. It still has the arrow functions.

**Comment by rullzer** [comment]
Should work now.
@michag86 can you test v1.0.3?

**Comment by michag86** [comment]
It works :heart_eyes:

Thank you!
