### ISSUE TITLE
Two-Factor Authentication via Nextcloud notification not working for non admin users

### ISSUE THREAD

**Issue by nikosranos** [nickv-nextcloud/twofactor_nextcloud_notification#455]
Hello there!
I have nextcloud 19.0.4
I have installed  Two-Factor Authentication via Nextcloud notification	
Everything Works fine if try to log in with admin but not with any other user, i dont receive any notifications.
Please  help me i really need this app

Thanks in advance

**Comment by nickvergessen** [comment]
There is no check for anything regarding admins, so it should work quite fine.
Can you check with a more recent Nextcloud version?
