### ISSUE TITLE
Confirmation from IOS does not work

### ISSUE THREAD

**Issue by marek-service** [nickv-nextcloud/twofactor_nextcloud_notification#468]
Verification does not work - the notification will come to the mobile application (ios), but the login confirmation will no longer be reflected in the login process on the website :-( 
We've tested it on different types of user accounts.

To make it possible for us to help you please fill out below information carefully.
--> 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by andyxheli** [comment]
Yes i can confirm this. I get a notification what Login attempt from x.x.x.x and if you click on it take you no where ere  to approve access but if you go to more notifications on the IOS app then you will see the notification and approve it so it dose work if you go that route.

**Comment by heliohenriques** [comment]
Hi,
Similar situation on NC v.22.2.0, but with Android.

**Comment by nickvergessen** [comment]
@heliohenriques 22.2.0 has another root cause, see https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-933234239

**Comment by nickvergessen** [comment]
Confirmation in iOS works (with patch in Nextcloud see above)
