### ISSUE TITLE
Does not work when the app Two Factor TOTP Provider is already enabled

### ISSUE THREAD

**Issue by DecaTec** [nickv-nextcloud/twofactor_nextcloud_notification#47]
This app doesn't seem to work as expected when the app Two Factor TOTP Provider is activated:

### Steps to reproduce
1. The app Two Factor TOTP Provider is already installed and set up.
2. Install TwoFactor via nextcloud notification and activate the auth method in the user's settings.
3. Try to log in on a different device.

### Expected behaviour
A notification should be shown on an already logged in device to accept the login request.

### Actual behaviour
No notifications are shown. You have to switch the auth method to the Two Factor TOTP Provider in order to log in.

**Nextcloud version:** 14.0.3

**List of activated apps:** Doesn't matter as long as the app Two Factor TOTP Provider is installed.

### Client configuration
**Browser:** Latest Firefox/Chrome

### Logs

No Log entries.

**Comment by rullzer** [comment]
Well if you have two providers you have to select this provider in order to get the notification send.

This works as expected on several instances of mine.

**Comment by DecaTec** [comment]
It looks like this provider is selected as default because I get the message to accept the notification in order to log in.
You even have the option to switch to the Two Factor TOTP Provider. In this case I have to do that because no notification is sent.

Maybe there are general problems if more two factor apps are activated?

**Comment by rullzer** [comment]
Can you make a screencast of what you do? Because here this all works as designed.

**Comment by DecaTec** [comment]
I don't think that we need a screencast here.
Step by step:

1. Nextcloud 14 with **no** two factor app installed.
2. Install Two Factor TOTP Provider from the app store
3. Enable Two Factor TOTP Provider in the user's settings.
4. Set up Two Factor TOTP Provider e.g. with Google Authenticator
5. Install twofactor_nextcloud_notification app from the app store
6. Enable twofactor_nextcloud_notification in the user's settings (leave Two Factor TOTP Provider enabled)
7. Now try to log in with another device (e.g. different browser)

Result: When trying to log in, I'll receive this message:
![screen](https://user-images.githubusercontent.com/9428899/48483495-dd529680-e813-11e8-94ee-d9bfff79d561.jpg)

Now, I don't get a notification on an already logged in device.

The only possibility to log in is now to click the link highlighted in the screenshot, because then the input of the Two Factor TOTP Provider is shown.

**Comment by rullzer** [comment]
Try clicking on the first item.

**Comment by DecaTec** [comment]
Well, yes of course!
Didn't realized that these where to links...

Sorry, my bad. 
Now it works as expected...

**Comment by ChristophWurst** [comment]
No worries. Thank you for your feedback!

**Comment by DecaTec** [comment]
Maybe it's a good idea not to use clickable links, but buttons for the 2nd factor options.
So the user would see, that he has three options here:
- 2nd factor as notification
- 2nd factor by TOTP
- Cancel longin

**Comment by ChristophWurst** [comment]
cc @jancborchardt ^
