### ISSUE TITLE
[FEATURE] Add the Accept and the Reject buttons directly in the notification

### ISSUE THREAD

**Issue by GLLM** [nickv-nextcloud/twofactor_nextcloud_notification#48]
Hello !

Thank you for this great & very useful app ! I now use this one daily :)

I'd like to have the 2 Accept & Reject buttons directly in the Notifications, so that I dont need to open the app to do either action.

Some apps (messaging/chat, for instance), do enable such buttons to do : Mark as read / Reply ....

Using :
* Nextcloud Server 14.0.3 on Ubuntu 18.04 LTS / MariaDB.
* Android 8.0 on Samsung S8+

Thank !
GLLM

**Comment by rullzer** [comment]
This is nothing this app controls. This is something that needs to be implemented on Android/IOS
