### ISSUE TITLE
Since Update 3.2.0 is no redirect to nextcloud 21 latest stable anymore after accepting the auth in the nextcloud android app

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nickv-nextcloud/twofactor_nextcloud_notification#538]
Reproduce:
Login
Press Accept in the nextcloud android app
==>
Nothing happens (see picture) it is stuck in the waiting process.
![image](https://user-images.githubusercontent.com/17781278/125903476-0beeb761-00c0-4a2e-8649-534f2374b799.png)

No redirect and also after reloud of the page it stays the same.
If you after accepting  the login open the root again: https://yourserver/nextcloud you are just back at the login:
![Pic2](https://user-images.githubusercontent.com/17781278/125903624-9928c781-3365-4ed8-b791-1763cd2e4be7.PNG)

**Comment by tonyskilton** [comment]
I am seeing the same behaviour with nextcloud 22.
I logged in as admin with a backup code. But was unable to disable the app. The security page shows a caution sign icon where the tick box should be.

**Comment by Kage1** [comment]
Same issue also, but I just upgraded to 21.0.3. It was working in 20.0.11. I get the notification on my device, I approve it, but I'm not getting past the approval screen. I also have the TOTP enable and that is working.

**Comment by gpgmailencrypt** [comment]
Same here on 21.0.3 . I could solve it temporarily by downgrading the app

**Comment by LunaticTazz** [comment]
Same behaviour on 20.0.10, 20.0.11 and 21.0.3 (as stated before).

**Comment by Emporea** [comment]
This is effecting me too. 

Ubuntu 18.04
Nextcloud 20.0.11
docker image

I am forced to use another option to login.

**Comment by WhiteBahamut** [comment]
Same for me on NC22 docker. Admin account stuck in redirect page.. user could use backup codes but Admin can't.

**Comment by franconianmetal** [comment]
3.2.0 does not proceed when accepting in nextcloud-app as 2fa-instance.
confirmed on NC 21.0.3 / debian9-proxmox-container 
no issue with nc-app (3.16.1) which had a similar issue previously

**Comment by vasyugan** [comment]
> 3.2.0 does not proceed when accepting in nextcloud-app as 2fa-instance.
> confirmed on NC 21.0.3 / debian9-proxmox-container
> no issue with nc-app (3.16.1) which had a similar issue previously
> 
> reverted to 3.1.2 -> works

It is a pity that you cannot download older versions from the appstore. Had to restore mine from a backup instead. I suppose that old releases are still downloadable from github, though. 

But this is quite a major bug, potentially locking many people out of their nextcloud instances. I am a bit concerned that so far the devs don't have responded.

**Comment by dnorak** [comment]
I experiment the same issue...
With NC 21 and 22 (docker version)
I think this is a major issue too, because it locking account...

**Comment by michag86** [comment]
I noticed that the js folder is completly missing.
After importing the js-folder from 3.1.2 and reverting this modification https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/commit/b48a2b8945299de6d2815ae6870630ff20578146 , it works again.

@nickvergessen

**Comment by nickvergessen** [comment]
What's actually missing is compiling the SJ from src/ into the js/ folder before I build the release package.
I will create a new package soon.

**Comment by nickvergessen** [comment]
New version packaged: https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/releases/tag/v3.2.1

Also uploaded to the appstore.

(Not) sorry it took so long. I'm on parental leave at the moment so only checking things very occasionally

**Comment by franconianmetal** [comment]
version 3.2.1 work,
thx

**Comment by WhiteBahamut** [comment]
also works for me again

**Comment by MrLoverLoverMMMM** [comment]
It works for me as well, thank you very much :)
