### ISSUE TITLE
CalDAV can't connect when enabling 2FA

### ISSUE THREAD

**Issue by LukaPitamic** [nickv-nextcloud/twofactor_nextcloud_notification#549]
I have Calendar app in Nextcloud connected to MacOS CalDAV.
When enabling mobile app 2FA through this app - CalDAV reports "Unable to verify account name or password"

![image](https://user-images.githubusercontent.com/34914144/134813443-2463c64c-9040-4584-a0f4-578b7af8d7b9.png)

How could this be solved? The communication between calendars is open all the time I guess, not?

**Comment by nickvergessen** [comment]
You need to use an app password (check your personal settings in the security tab)
