### ISSUE TITLE
the asked method is not supported

### ISSUE THREAD

**Issue by olsins** [nickv-nextcloud/twofactor_nextcloud_notification#550]
### Steps to reproduce
1. Login into nextcloud using twofactor_nextcloud_notification
2. receive option on iphone to allow login

### Expected behaviour
Tell us what should happen
being able to login

### Actual behaviour
Tell us what happens instead
 after pressing "allow" a message ist displayed: "Fehler 405: Die angeforderte Methode wird nicht unterstützt. - the asked method is not supported

Also it is not possible to allow acces over another computer logged in - the error is show: "Die Aktion konnte nicht gefunden werden" -the action could not be found

what is weird - over the nextcoud client app for mac it is possible to give permission when the app (on the mac) is rebooted bevor.

### Server configuration

**Operating system**:
raspberry - OS
**Web server:**
apache
**Database:**
mysql
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
21.04
**Where did you install Nextcloud from:**
nextcloudpi
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
This should be a bug in the iOS app then.

**Comment by olsins** [comment]
Well the error also appears when logged in to another computer and the allow button is pressed over the browser - the error is show: "Die Aktion konnte nicht gefunden werden" -the action could not be found.

but which I have to admit is, that i recently updated to ios 15 - does anyone else have this error?

**Comment by nickvergessen** [comment]
I will check tomorrow (my iPad is 15 too), but sounds like duplicate of #468

**Comment by olsins** [comment]
okay issue is closed - I had to change 'overwriteprotocol' => 'http' to 'overwriteprotocol' => 'https' - I have no clue why it had been changed automatically.
