### ISSUE TITLE
Issue with NC v.22.2.0

### ISSUE THREAD

**Issue by heliohenriques** [nickv-nextcloud/twofactor_nextcloud_notification#551]
Hi,
Today after update to the version 22.2.0, the 2FA APP Notification stop work.
The issue happened with different account's and different users. 
Some phones don't receive notification, and some receive, but after approval nothing happen. 
The same with approval by webApp notification (after approval nothing happen). 

The login keeps waiting permission, but nothing happen.

No logs were created. 

### Server configuration
**Operating system: Debian 10
**Web server: Apache
**Database: SQL
**PHP version: 8.0
**Nextcloud version: 22.2.0

Thank you for the help

**Comment by nickvergessen** [comment]
So there is a known issue with iOS: https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/468

**Comment by tonyskilton** [comment]
I'm seeing the same behaviour.

Notification is generated on the Android app, and is showing up in the Windows and Linux desktop clients.
Clicking approve on any of them doesn't progress the login, it just stays on the "Please accept the request" screen.

This has been since updating to 22.2.0

Nothing appears in the log.

Server configuration
**Operating system: openSUSE Tumbleweed
**Web server: Apache
**Database: MariaDB
**PHP version: 7.4
**Nextcloud version: 22.2.0

**Comment by freddresken** [comment]
Same here on OpenSUSE Leap 15.3.  Only OTP seem to function properly.

**Comment by schnello** [comment]
Same here. No Log.
PhP 8.0.11
Nextcloud version: 22.2.0
Ubuntu Server

**Comment by Seneliux** [comment]
nginx shows that there are many GET requests, and only stops when canceling login. Same before Aprove, and after approving login. Even after canceling login via notification nothing changing. Requests stops if cancel login at login prompt (not via notification)
NC "ignoring" Accept or Cancel login and infinity generates GET requests.

> IP - - [03/Oct/2021:20:09:02 +0200] "GET /ocs/v2.php/apps/twofactor_nextcloud_notification/api/v1/poll/TOKEN HTTP/2.0" 303 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36" "-"
> IP - - [03/Oct/2021:20:11:33 +0200] "GET /login/selectchallenge?redirect_url=/ocs/v2.php/apps/twofactor_nextcloud_notification/api/v1/poll/TOKEN HTTP/2.0" 200 7387 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36" "-"
> IP - - [03/Oct/2021:20:13:02 +0200] "GET /login/selectchallenge?redirect_url=/ocs/v2.php/apps/twofactor_nextcloud_notification/api/v1/poll/TOKEN HTTP/2.0" 200 7385 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36" "-"

**Comment by nickvergessen** [comment]
The reason is this security hardening:
https://github.com/nextcloud/server/pull/28725

**Comment by nickvergessen** [comment]
This patch in Nextcloud itself (not the app) should solve the problem:
https://github.com/nextcloud/server/pull/29056.diff

See https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html for a manual how to apply the patch

**Comment by DecaTec** [comment]
> This patch in Nextcloud itself (not the app) should solve the problem: https://github.com/nextcloud/server/pull/29056.diff
> 

Yes, this seems to work.
Thank you!

**Comment by heliohenriques** [comment]
> This patch in Nextcloud itself (not the app) should solve the problem: https://github.com/nextcloud/server/pull/29056.diff
> 
> See https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html for a manual how to apply the patch

It works.
Thank you!

**Comment by franconianmetal** [comment]
patch works, thx

**Comment by resoli** [comment]
Patch fixes for me (NC 21.0.5) as well. Thanks.

**Comment by webermax** [comment]
Works for 21.0.5. Thank you!

`sudo -u www-data wget https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/29056.diff`
`sudo -u www-data git apply --reject 29056.diff`

**Comment by webermax** [comment]
> > There is no psalm.xml in my installation and patch asks for this file.
> 
> Me too but the patch works. Did the command from [#551 (comment)](https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-939814759) This is for version 22.2.0

`--reject` applies partly: https://git-scm.com/docs/git-apply

**Comment by pvanthony** [comment]
> > Me too but the patch works. Did the command from [#551 (comment)](https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-939814759) This is for version 22.2.0
> 
> `--reject` applies partly: https://git-scm.com/docs/git-apply

Cool. Just read the doc at the link above. Thank you for sharing the link to the documentation.

**Comment by Webbeh** [comment]
This patch worked for me today as well. Nextcloud 22.2.0.

Thank you !

**Comment by meonkeys** [comment]
> How to patch a snap installation on a read-only filesystem?

Similar question: how would I patch Nextcloud 22.2.0 run via Docker compose? I'm using the Docker image label `nextcloud:22`. I'm guessing something could be added to `docker-compose.yml` to run [some of] the shell commands mentioned by others, or that I'd need to build a custom image.

Or wait for the next minor release... Will Nextcloud server 22.2.1 include the fix?

**Comment by nickvergessen** [comment]
> Will Nextcloud server 22.2.1 include the fix?

yes, and it was released yesterday. So whenever the docker people pick it up you have it

**Comment by Darkmagister** [comment]
i have nextcloud 22.2.1 but i still have this issue, i don't want to apply the patch manually because it would need to be done every update, maybe 22.2.2 will have it ???

**Comment by nickvergessen** [comment]
22.2.2 is already there and the patch is included in 22.2.1 already.
If you still have an issue it might be something else

**Comment by meonkeys** [comment]
Heads up, Docker users: make sure you skip v22.2.1 ( https://hub.docker.com/_/nextcloud says that's still the latest stable v22, so wait until 22.2.2 is out before updating!) The relevant issue is https://github.com/nextcloud/server/issues/29678

**Comment by Darkmagister** [comment]
> 22.2.2 is already there and the patch is included in 22.2.1 already. If you still have an issue it might be something else

I will wait for docker update of image to 20.2.2 to be sure but with 20.2.1 i still have this issue, i accept the login from the notification on the app but the page on the computer doesn't refresh or anything

**Comment by meonkeys** [comment]
Verified fixed / working as expected with nextcloud 22.2.3 (using image from Docker Hub).

**Comment by 1989gironimo** [comment]
I'm running 22.2.3 and it's still not working, what's needed to analyze this further?
