### ISSUE TITLE
two-factor auth provider 'twofactor_webauthn' failed to load

### ISSUE THREAD

**Issue by DecaTec** [nickv-nextcloud/twofactor_nextcloud_notification#555]
I think this started after the update to 21.0.5.
The NC logs do not provide a useful message. The same is true for the browser's console.

### Steps to reproduce
1. With app twofactor_nextcloud_notification installed and option in the personal settings activated.
2. Log in.
3. Chose notofication as 2nd factor
4. Accept the notification on a second device

### Expected behaviour
The user should get logged in.

### Actual behaviour
Nothing happens.

### Server configuration
**Operating system**:
Ubuntu 

**Web server:**
nginx

**Database:**
PostgreSQL

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21.0.5 

### Client configuration
**Browser:**
Doesn't matter.

**Operating system:**
Doesn't matter

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"1Rb0UpCA7Bxutcjz4ID6","level":3,"time":"2021-10-02T14:55:15+02:00","remoteAddr":"192.168.xxx.xxx","user":"xxx","app":"core","method":"GET","url":"/login/selectchallenge?redirect_url=/ocs/v2.php/apps/twofactor_nextcloud_notification/api/v1/poll/J4IuhTP5ez4A88VRMdJRUSRe00rRwiHByx1qfzcA","message":"1 two-factor auth providers failed to load","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0","version":"21.0.5.1"}

```

#### Browser log
```
poll.js:26 promise rejected: TypeError: Cannot read properties of undefined (reading 'data')
    at challenge.js:37

```

**Comment by gpgmailencrypt** [comment]
same here. It definitely started with the 21.0.5 update

**Comment by Larx** [comment]
Same here after 21.0.5 update. Login with OTP still works, however.

**Comment by franconianmetal** [comment]
Same here after update to 22.2.0

**Comment by nickvergessen** [comment]
Can you please post the list of apps you have active?

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder

**Comment by franconianmetal** [comment]
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - bookmarks: 10.0.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - drawio: 1.0.1
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_antivirus: 3.2.2
  - files_external: 1.13.0
  - files_fulltextsearch: 22.0.1
  - files_markdown: 2.3.4
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - geoblocker: 0.5.1
  - keeweb: 0.6.6
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.9
  - music: 1.3.3
  - news: 16.0.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - rainloop: 7.1.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_nextcloud_notification: 3.2.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_notifications
  - carnet
  - dashboard
  - deck
  - ehr
  - encryption
  - firstrunwizard
  - mail
  - occweb
  - qownnotesapi
  - quicknotes
  - ransomware_protection
  - survey_client
  - systemtags
  - user_ldap
  - whiteboard
`
`

**Comment by DecaTec** [comment]
Here's my app list.
The problem can also be reproduced on another instance which is on version 22.2.0.

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - apporder: 0.13.0
  - bookmarks: 10.0.0
  - breezedark: 21.0.10
  - calendar: 2.3.4
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - cookbook: 0.9.4
  - dashboard: 7.1.0
  - dav: 1.17.1
  - drawio: 1.0.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_automatedtagging: 1.11.0
  - files_external: 1.12.0
  - files_fulltextsearch: 21.0.4
  - files_fulltextsearch_tesseract: 20.0.1
  - files_markdown: 2.3.4
  - files_pdfviewer: 2.1.0
  - files_photospheres: 1.21.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - fulltextsearch: 21.0.3
  - fulltextsearch_elasticsearch: 21.0.2
  - groupfolders: 9.0.3
  - integration_github: 1.0.0
  - integration_gitlab: 1.0.0
  - integration_mastodon: 1.0.0
  - integration_twitter: 1.0.0
  - keeweb: 0.6.6
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - metadata: 0.14.0
  - news: 16.0.1
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - notify_push: 0.2.4
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recognize: 1.6.10
  - richdocuments: 4.2.3
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.3.2
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.2.1
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflow_ocr: 1.21.1
  - workflowengine: 2.3.1
Disabled:
  - admin_audit
  - announcementcenter
  - encryption
  - recommendations
  - support
  - survey_client
  - twofactor_admin
  - user_ldap

**Comment by nickvergessen** [comment]
Can you try https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-933234239

**Comment by DecaTec** [comment]
> Can you try [#551 (comment)](https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-933234239)

With the patch applied, it works right now.
