### ISSUE TITLE
Sinsce Nextcloud Version 21.0.5 it does not authentificate correctly anymore

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nickv-nextcloud/twofactor_nextcloud_notification#556]
NC Server: 21.0.5
NC App Android: 3.17.0

Problem Description: If an admin is using the tfa with the app-login, it pops up correctly at the app. He improves, but nc does not redirect or authentificate, because if you reload you will be still stuck at the waiting for confirmation screen.

How to reproduce:
1.) Update to 21.0.5
2.) Authentificate as an admin
3.) Click approve at Android or Ios
4.) Hangs, no entry anymore

**Comment by nickvergessen** [comment]
https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-933234239
