### ISSUE TITLE
approval not working in 22.2

### ISSUE THREAD

**Issue by jared2876** [nickv-nextcloud/twofactor_nextcloud_notification#558]
### Steps to reproduce
1. Log in with username and password
2. notification shows up like expected
3. click or tap approve
4. notification dismisses but login stays on 2fa screen.

### Expected behaviour
when tapping approve on the notification the user should be logged in.

### Actual behaviour
when pressing approve on the 2fa notification the notification will dismiss but the user will not be logged in. The display will stay on the check for notification screen.

This occurs on both browsers and mobile as well as mobile apps.
The nextcloud instance is running on unraid 6.9.2 through a docker container. This happened after updating to Nextcloud 22.2.

**Comment by nickvergessen** [comment]
https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/551#issuecomment-933234239
