### ISSUE TITLE
Davdroid not working

### ISSUE THREAD

**Issue by fankijo** [nickv-nextcloud/twofactor_nextcloud_notification#58]
Hi,

after enabling the App and checking the checkbox to use it for my user, the davdroid app stopped to work. It first said that my login credentials arent right anymore. I then reconfigured the app, but I cant get it to work.
After disabling the two factor auth for my user davdroid instantly works again.

### Steps to reproduce
1. Configure Davdroid on Android smartphone to sync contacts/calendars
2. install and enable 2FA App
3. sync davdroid manually and the error appears

**Comment by rullzer** [comment]
If you have 2FA enabled you need to setup an app password for davdroid.

**Comment by fankijo** [comment]
Thanks, with the app Password it works!
