### ISSUE TITLE
Show actual IP when routed via nginx

### ISSUE THREAD

**Issue by tisboyo** [nickv-nextcloud/twofactor_nextcloud_notification#80]
### Steps to reproduce
1. Route nextcloud through nginx with proxy_pass
2. Have proxy headings in nginx config file

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                add_header Front-End-Https on;
                add_header Strict-Transport-Security "max-age=31536000;" always;
                proxy_ssl_verify off;
                proxy_pass https://192.168.xxx.xxx

### Expected behaviour
Tell us what should happen
Notification should show actual IP address not nginx's IP.

### Actual behaviour
Tell us what happens instead
All requests appear to be routing from nginx

**Comment by rullzer** [comment]
We request the ip from Nextcloud so it is handled there.
But it seems your trusted proxies are not properly configured if you get the ip of nginx.

**Comment by tisboyo** [comment]
That was the answer, to a setting I didn't know existed. 
For those who may stumble upon this in the future, https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html

Also, when accessing through hairpin nat it started to give the ip of my router instead of the local network ip, so setting the nginx ip manually to my nextcloud domain in my local dns server (pihole) fixed that problem as well. All is working, thanks for pointing me in the right direction @rullzer
